#!/bin/bash

# 自动执行的批处理：HomeBrew \ Mas \ MacPorts \ TopGrade \ MacUpdater

#设置执行所需的 环境变量！
export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH


# ================================================================================================
# 参数设置：用户可修改 （Start）
# ================================================================================================

# 设置 ：本脚本拒绝执行的时间范围
STOP_TIME="03:00"       # 拒绝执行 的 结束时间（这个时间后任务正常运行）
DURATION_MINUTES=10     # 拒绝执行结束前 的 时间长度（10分钟，意味着从 2:50 - 3:00 , 本脚本拒绝执行） 注意，单位：分钟（注意，单位不是秒！！！）

# 路径：保存日志文件的路径
ICLOUD_PATH="$HOME/Library/Mobile Documents/com~apple~CloudDocs"            # 获取 iCloud 云盘路径，
COMPUTER_NAME=$(scutil --get ComputerName)                                  # 获取 本机名称（并以本机名称作为子文件夹名称）
LOG_PATH="$ICLOUD_PATH/LOG/$COMPUTER_NAME"                                  # LOG 日志文件 的 保存路径
mkdir -p "$LOG_PATH"                                                        # 创建目录   # 注意：这里是保存到iCloud，也可以设置别的保存路径

# ================================================================================================
# 参数设置：用户可修改 （End）
# ================================================================================================




# ---------------------------------------
# 参数设置：不建议用户修改
# ---------------------------------------

# 定义：日志文件
LOG_FULL_LAST="$LOG_PATH/--UpdateFull.--Last--.log"
LOG_FILE="$LOG_PATH/Update_Auto.log"
LOG_FULL_FILE="$LOG_PATH/UpdateFull.$(date +%Y-%m).log"
LOG_ERROR_FILE="$LOG_PATH/Update_Error.log"
LOG_MACUPDATER_FILE="$LOG_PATH/Update_MacUpdater.log"
echo -e "" > "$LOG_MACUPDATER_FILE"

# 定义：被测试的外网网址（需要翻墙的网址）
TARGET_1="github.com"
TARGET_2="brew.sh"
TARGET_3="apps.apple.com/us/app/apple-store/id375380948"
TARGET_4="macupdater.com"
# 如果不能访问上述网站，会导致很多软件都 更新失败。

# 定义 MacUpdater 客户端路径
MACUPDATER_CLIENT="/Applications/MacUpdater.app/Contents/Resources/macupdater_client"




# ---------------------------------------
# 自定义函数
# ---------------------------------------

# ************************* #
# 定义函数：检查时间范围的函数
# ************************* #
check_time_range() {
  local stop_time="$1"           # 停止时间
  local duration_minutes="$2"    # 执行时长（分钟）
  local LOG_ERROR_FILE="$3"      # 日志文件

  # 计算起始时间并确保格式为 HH:MM
  local stop_time_seconds start_time
  stop_time_seconds=$(date -j -f "%H:%M" "$stop_time" "+%s") # 将停止时间转换为时间戳
  start_time=$(date -j -f "%s" $((stop_time_seconds - duration_minutes * 60)) "+%H:%M") # 计算起始时间，并转为 HH:MM 格式

  # 获取当前时间
  local current_time
  current_time=$(date '+%H:%M')

  # 检查当前时间是否在范围内
  if [[ "$current_time" > "$start_time" && "$current_time" < "$stop_time" ]]; then
    printf "\033[1;31m[STOP]\033[0m  "
    printf "[STOP] "                                                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"  > /dev/null 
    echo -e "任务退出（$(date '+%Y-%m-%d %H:%M:%S')）：为避免与预设 定时任务 冲突"      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" "$LOG_ERROR_FILE" 
    printf "\033[1;31m[STOP]\033[0m  "
    printf "[STOP] "                                                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"  > /dev/null 
    echo -e "时间范围（停止建立 更新任务）：$start_time - $stop_time"                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" "$LOG_ERROR_FILE" 
    exit
  fi
}

# ************************* #
# 自定义函数：检查连接的函数
# ************************* #
check_connection() {
  local target=$1
  local LOG_FILE=$2

  if curl -I --connect-timeout 5 "$target" > /dev/null 2>&1; then
    printf "\033[1;32m[OK]\033[0m   "  
    printf "[OK]   "                                                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"  > /dev/null  
    printf "已连通 [$target] \n"                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"   
    return 0
  else
    printf "\033[1;31m[ERROR]\033[0m " 
    printf "[ERROR] "                                                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" "$LOG_FILE"  > /dev/null  
    echo -e "[$target] $(date '+%Y-%m-%d %H:%M:%S') 连接失败，等待10秒后重试..."        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" "$LOG_FILE"  
    sleep 10
    return 1
  fi
}

# ************************* #
# 自定义函数：显示进度条
# ************************* #
show_progress() {
    # 可输入的变量
    local scanned=$1
    local unrecognized=$2
    local to_update=$3
    local total=$4

    # 定义进度条长度（注意：折行，会导致刷新异常！！！！！）
    local bar_width=20

    # 防止除以零
    if [ "$total" -eq 0 ]; then
        total=1
    fi

    # 计算百分比
    local percent=$(( scanned * 100 / total ))

    # 生成进度条
    local filled=$(( scanned * bar_width / total ))
    local empty=$(( bar_width - filled ))
    local bar=""
    for ((i=0; i<filled; i++)); do bar+="█"; done
    for ((i=0; i<empty; i++)); do bar+="-"; done

    # 打印进度条到终端
    printf "\r进度: [%-${bar_width}s] %d%% | 未识别: %d | 需更新: %d | 已扫描: %d/%d" \
        "$bar" "$percent" "$unrecognized" "$to_update" "$scanned" "$total" > /dev/tty
}

# ************************* #
# 自定义函数：运行命令并处理输出
# ************************* #
run_command_with_show_progress() {
    # 可输入的变量
    local CMD="$1"
    local MODE="$2" # SCAN 或 UPDATE
    local LOCAL_LOG_FILE="$3" # 

    # 初始化进度变量
    local scanned=0
    local unrecognized=0
    local to_update=0

    # 日志记录开始执行的命令
    echo -e "执行命令: $CMD"         | tee -a "$LOCAL_LOG_FILE"

    # 执行命令并实时处理输出
    eval "$CMD" 2>&1         | tee -a "$LOCAL_LOG_FILE" | while IFS= read -r line; do
        # 检查是否为 'Scan did stop scanning' 的行
        if [[ "$line" =~ Scan\ did\ stop\ scanning\ \'[^\']+\'\ app\.\.\. ]]; then
            ((scanned++))
            show_progress "$scanned" "$unrecognized" "$to_update" "$TOTAL_APPS"
        fi

        # 记录每一行到日志文件
        echo -e "$line" >> "$LOCAL_LOG_FILE"
    done

    # 完成后换行（避免下次输出覆盖进度条）
    echo -e "" > /dev/tty
    echo -e ""         | tee -a "$LOCAL_LOG_FILE"
}



# ************************* #
# 自定义函数：恢复 Launchpad 和 桌面布局
# ************************* #
restore_desktop_layout() {
    PATH_DesktopLayout_SOURCE1="$HOME/Library/Preferences"

    if [ -z "$PARENT_DIR" ]; then
        USER_ID=$(basename "$(dirname "$TMPDIR")")
        PARENT_DIR=$(find /System/Volumes/Data/private/var/folders/ -maxdepth 2 -type d -name "$USER_ID" 2>/dev/null)
    fi

    PATH_DesktopLayout_SOURCE2="$PARENT_DIR/0"

    if [ ! -f "$PATH_DesktopLayout_BACKUP/com.apple.spaces.plist" ] || \
       [ ! -f "$PATH_DesktopLayout_BACKUP/com.apple.dock.plist" ] || \
       [ ! -d "$PATH_DesktopLayout_BACKUP/com.apple.dock.launchpad" ]; then
        printf  "\033[1;34m[Info]\033[0m "
        printf  "[Info] "                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
        echo -e "错误：备份文件不完整，无法恢复 桌面布局"                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    else
        printf  "\033[1;34m[Info]\033[0m "
        printf  "[Info] "                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null  
        echo -e "开始还原 桌面布局 ... "                                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        cp -f   "$PATH_DesktopLayout_BACKUP/com.apple.spaces.plist"       "$PATH_DesktopLayout_SOURCE1/com.apple.spaces.plist"
        cp -f   "$PATH_DesktopLayout_BACKUP/com.apple.dock.plist"         "$PATH_DesktopLayout_SOURCE1/com.apple.dock.plist"
        sudo cp -rf "$PATH_DesktopLayout_BACKUP/com.apple.dock.launchpad" "$PATH_DesktopLayout_SOURCE2"
        printf  "\033[1;34m[Info]\033[0m "
        printf  "[Info] "                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null  
        echo -e "正在重启 桌面布局 ... "                                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        killall Dock
    fi

}




# -----------------------------------------------
# 检查 & 创建 ：Log日志文件
# -----------------------------------------------

# 重置LOG_FULL_LAST日志文件
cat /dev/null > "$LOG_FULL_LAST"

# 检查LOG_FILE日志文件是否存在
if [ ! -f "$LOG_FILE" ]; then
    # 文件不存在，创建文件
    touch "$LOG_FILE"
fi

# 检查LOG_ERROR_FILE日志文件是否存在
if [ ! -f "$LOG_ERROR_FILE" ]; then
    # 文件不存在，创建文件
    touch "$LOG_ERROR_FILE"
fi

# 检查LOG_FULL_FILE日志文件是否存在
if [ ! -f "$LOG_FULL_FILE" ]; then
    # 文件不存在，创建文件
    touch "$LOG_FULL_FILE"
else
    # 文件存在，检查文件大小
    FILE_SIZE=$(stat -f%z "$LOG_FULL_FILE") # macOS 使用 stat -f%z

    if [ "$FILE_SIZE" -gt 10 ]; then
        # 如果文件大小超过100字节，执行以下操作
        echo -e "" >> "$LOG_FULL_FILE"
        echo -e "" >> "$LOG_FULL_FILE"
        echo -e "" >> "$LOG_FULL_FILE"
        echo -e "" >> "$LOG_FULL_FILE"
        echo -e "" >> "$LOG_FULL_FILE"
        echo -e "" >> "$LOG_FULL_FILE"
    fi
fi

# 初始化 MacUpdater 日志文件
echo -e "MacUpdater 执行日志 - $(date)" > "$LOG_MACUPDATER_FILE"



# ---------------------------------------
# 检测：外网是否能正常访问
# ---------------------------------------

echo $PWD

echo -e ""                                                                              | tee -a "$LOG_ERROR_FILE"
echo -e "-------------------------------------------------------------------"           | tee -a "$LOG_ERROR_FILE" > /dev/null
echo -e "" >> "$LOG_ERROR_FILE"
echo -e "[自动更新]  $(date '+%Y-%m-%d %H:%M:%S')  "                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" "$LOG_ERROR_FILE" 
echo -e "======================================================================="       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
printf  "测试网络（海外 HTTPS 连接） ...  ｜  "                                         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" "$LOG_ERROR_FILE" 
echo -e "当前工作目录 = '$PWD' "                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" "$LOG_ERROR_FILE" 
echo -e ""                                                                              | tee -a "$LOG_ERROR_FILE" > /dev/null

# 轮询检查网络连通性
while true; do

  # 调用检查时间范围函数
  check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"

  # 检查 TARGET_1 的连接
  if ! check_connection "$TARGET_1" "$LOG_ERROR_FILE"; then
    continue # 如果连接失败，重新开始循环
  fi

  # 检查 TARGET_2 的连接
  if ! check_connection "$TARGET_2" "$LOG_ERROR_FILE"; then
    continue # 如果连接失败，重新开始循环
  fi

  # 检查 TARGET_3 的连接
  if ! check_connection "$TARGET_3" "$LOG_ERROR_FILE"; then
    continue # 如果连接失败，重新开始循环
  fi

  # 检查 TARGET_4 的连接
  if ! check_connection "$TARGET_4" "$LOG_ERROR_FILE"; then
    continue # 如果连接失败，重新开始循环
  fi

  # 如果N个目标，都成功连接，退出循环
  printf "\033[1;32m[OK]\033[0m   "  
  printf "[OK]   "                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
  echo -e "海外 HTTPS 连接正常 ... !!!! "                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
  break
done

echo -e "======================================================================="       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"




# -----------------------------------------------
# 检查 1 ：Homebrew 是否安装（并更新）
# -----------------------------------------------

echo -e "测试安装环境：$(date '+%Y-%m-%d %H:%M:%S') ..."                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"  

echo -e "\033[1;36m-----------------------------------------------\033[0m" 
echo -e "\033[1;36m 检测 “Homebrew与系统架构” 是否匹配 ...        \033[0m"
echo -e "\033[1;36m-----------------------------------------------\033[0m" 

echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "检测 “Homebrew与系统架构” 是否匹配"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 

# 检测系统架构

architecture=$(uname -m)

if [ "$architecture" = "arm64" ]; then

    # 检查 Homebrew 是否已安装
    if ! command -v brew > /dev/null 2>&1 ; then

        printf  "\033[1;34m[INFO]\033[0m "
        printf  "[INFO] "                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
        echo -e "未检测到 Homebrew，开始安装 Homebrew ..."                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
        # 添加 Homebrew 到环境变量
        echo -e 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"
        
        printf  "\033[1;34m[INFO]\033[0m "
        printf  "[INFO] "                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
        echo -e "Homebrew 安装完成。"                                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        echo -e ""                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        exit 0
    fi

    # 获取 Homebrew 的 安装路径
    brew_path=$(brew --prefix)
    printf  "\033[1;34m[INFO]\033[0m "
    printf  "[INFO] "                                                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "Homebrew目录 : '$brew_path'"                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    # 获取 CPU 的 处理器指令集
    cpu_isa=$(uname -m)
    printf  "\033[1;34m[INFO]\033[0m "
    printf  "[INFO] "                                                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "CPU   指令集 : '$cpu_isa'"                                                 | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    # 获取 CPU 的 芯片型号
    cpu_chip=$(sysctl -n machdep.cpu.brand_string)
    printf  "\033[1;34m[INFO]\033[0m "
    printf  "[INFO] "                                                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "CPU 芯片型号 : '$cpu_chip'"                                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    
   #echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    if [[ $cpu_isa == "arm64" && $brew_path == "/opt/homebrew" ]]; then
        printf  "\033[1;32m[OK]\033[0m   "
        printf  "[OK]   "                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
        echo -e "Homebrew 无需更改"                                                     | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        # 更新 Homebrew
        echo -e ""                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        echo -e ""                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 

        echo -e "\033[1;36m-----------------------------------------------\033[0m" 
        echo -e "\033[1;36m 更新 Homebrew 工具 ...\033[0m"
        echo -e "\033[1;36m-----------------------------------------------\033[0m" 

        echo -e "----------------------------------"                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
        echo -e "更新 Homebrew 工具 "                                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
        echo -e "----------------------------------"                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null

        echo -e ""                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 

        brew update --force 2>&1                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

        echo -e ""                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 

        # exit 0

     elif [[ $cpu_isa == "arm64" && $brew_path == "/usr/local" ]]; then

        printf  "\033[1;31m[ERROR]\033[0m "
        printf  "[ERROR] "                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
        echo -e "检测到当前 Homebrew 为 x86_64 版本，准备切换为 ARM 版本。"             | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        
        # exit 0   # 调试使用！！！

        # 提示用户确认卸载 x86_64 版本的 Homebrew
        #read -p "此操作将卸载 x86_64 版本的 Homebrew，并安装 ARM 版本。是否继续？(y/N): " confirm
        #if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        #    print_info "取消操作。"
        #    exit 0
        #fi

        # 卸载 x86_64 版本的 Homebrew
        printf  "\033[1;34m[INFO]\033[0m "
        printf  "[INFO] "                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
        echo -e "正在卸载 x86_64 版本的 Homebrew..."                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"                         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        
        # 安装 ARM 版本的 Homebrew
        printf  "\033[1;34m[INFO]\033[0m "
        printf  "[INFO] "                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
        echo -e "正在安装 ARM 版本的 Homebrew..."                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        # 非交互式安装
        NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        
        # 添加 Homebrew 到环境变量
        echo -e 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"
        
        printf  "\033[1;34m[INFO]\033[0m "
        printf  "[INFO] "                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
        echo -e "ARM 版本的 Homebrew 安装完成。"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

        # 获取 Homebrew 的安装路径
        brew_newpath=$(which brew)
        printf  "\033[1;34m[INFO]\033[0m "
        printf  "[INFO] "                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
        echo -e "检测到 Homebrew 安装路径: $brew_newpath"                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

        if [[ $brew_newpath == /opt/homebrew/* ]]; then
            printf  "\033[1;32m[OK]\033[0m $1"
            printf  "[OK]   "                                                           | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
            echo -e "验证结果：当前 Homebrew 为 ARM 版本。"                             | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
            echo -e ""                                                                  | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        elif [[ $brew_newpath == /usr/local/* ]]; then
            printf  "\033[1;31m[ERROR]\033[0m "
            printf  "[ERROR] "                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
            echo -e "验证结果：检测到当前 Homebrew 为 x86_64 版本。退出"                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
            echo -e ""                                                                  | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        else
            printf  "\033[1;31m[ERROR]\033[0m "
            echo -e "验证结果：检测未知版本。退出"                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
            printf  "[ERROR] "                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
            echo -e ""                                                                  | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        fi

    else
        print_error "未知的 Homebrew 安装路径: $brew_path"                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        echo -e ""                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    fi

else
    printf "当前系统不是 ARM 架构 (Apple Silicon)，本脚本暂不支持。"                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    exit 0 
fi







# ------------------------------------------------
# 检查 2 ：其他Homebrew工具 是否安装（并更新）
# ------------------------------------------------

# 调用检查时间范围函数
check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"

if ! brew list | grep -q "^jq$" || ! brew list | grep -q "^coreutils$" || ! brew list | grep -q "^parallel$" || ! brew list | grep -q "^aria2$";  then
    echo -e ""                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "\033[1;36m 安装 其他必备工具 ...\033[0m"
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 

    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "安装 其他必备工具 "                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
fi

if ! brew list | grep -q "^aria2$"; then
    printf  "\033[1;34m[INFO]\033[0m "
    echo -e "[安装] aria2 ..."                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    brew install aria2                                                                  | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
fi

if ! brew list | grep -q "^parallel$"; then
    printf  "\033[1;34m[INFO]\033[0m "
    echo -e "[安装] parallel ..."                                                       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    brew install parallel                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
fi

if ! brew list | grep -q "^coreutils$"; then
    printf  "\033[1;34m[INFO]\033[0m "
    echo -e "[安装] coreutils ..."                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    brew install coreutils                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
fi

if ! brew list | grep -q "^jq$"; then
    printf  "\033[1;34m[INFO]\033[0m "
    echo -e "[安装] jq ..."                                                             | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    brew install jq                                                                     | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
fi

if ! brew tap | grep -q '^buo/cask-upgrade$'; then
    printf  "\033[1;34m[INFO]\033[0m "
    echo -e "[安装] buo/cask-upgrad ..."                                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    brew tap buo/cask-upgrade                                                           | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
fi



# -----------------------------------------------
# 检查 3 ：Mas 是否安装（并更新）
# -----------------------------------------------

# 调用检查时间范围函数
check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"

if brew list --formula | grep -q "^mas\$"; then
    echo -e ""                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "\033[1;36m 更新 Mas 工具 ...\033[0m"
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "更新 Mas 工具"                                                             | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    brew upgrade --greedy --force mas 2>&1                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
else
    echo -e ""                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "\033[1;36m Mas 未安装，开始安装 ...\033[0m"
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "Mas 未安装，开始安装"                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    brew reinstall --force mas 2>&1                                                     | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
   #echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    if [ $? -eq 0 ]; then
        echo -e "Mas 安装成功。"                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    else
        echo -e "Mas 安装失败。"                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    fi
fi





# -----------------------------------------------
# 检查 4 ：MacPorts 是否安装（并更新）
# -----------------------------------------------

# 调用检查时间范围函数
check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"

if port version  > /dev/null 2>&1 ; then
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "\033[1;36m 更新 MacPorts 工具 ...\033[0m"
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "更新 MacPorts 工具  "                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    sudo port selfupdate 2>&1                                                           | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
else
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "\033[1;36m MacPorts 未安装，开始安装 ...\033[0m"
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "MacPorts 未安装，开始安装  "                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    curl -LO https://distfiles.macports.org/MacPorts/MacPorts-2.8.1-10.15-Catalina.pkg && sudo /usr/sbin/installer -pkg MacPorts-2.8.1-10.15-Catalina.pkg -target /
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    if [ $? -eq 0 ]; then
        echo -e "MacPorts 安装成功。"                                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        echo -e ""                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    else
        echo -e "MacPorts 安装失败。"                                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        echo -e ""                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    fi
fi








# -----------------------------------------------
# 检查 5 ：TopGrade 是否安装（并更新）
# -----------------------------------------------

# 调用检查时间范围函数
check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"

if brew list --formula | grep -q "^topgrade\$"; then
    echo -e ""                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "\033[1;36m 更新 TopGrade 工具 ...\033[0m"
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "更新 TopGrade 工具"                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    brew upgrade --greedy topgrade 2>&1                                                 | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
else
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "\033[1;36m TopGrade 未安装，开始安装 ...\033[0m"
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "TopGrade 未安装，开始安装"                                                 | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    brew reinstall --force topgrade 2>&1                                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    if [ $? -eq 0 ]; then
        echo -e "TopGrade 安装成功。"                                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        echo -e ""                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    else
        echo -e "TopGrade 安装失败。"                                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    fi
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
fi




# ------------------------------------------------
# 检查 6 ：MacUpdater 是否安装（并更新）
# ------------------------------------------------

# 调用检查时间范围函数
check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"

if brew list --cask | grep -q "^macupdater\$"; then
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "\033[1;36m 更新 MacUpdater 工具 ...\033[0m"
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "更新 MacUpdater 工具"                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    brew upgrade --greedy --cask --force macupdater 2>&1                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
  # 功能：只检查 macupdater 是否过期，若过期则静默强制重装，否则跳过
  # if brew outdated --cask --greedy macupdater| grep -q '^macupdater$'; then
  #   echo -e "检测到 macupdater 有新版本，开始静默升级…"
  #   brew reinstall --cask --force macupdater
  #   echo -e "macupdater 已静默升级完成。"
  # else
  #   echo -e "macupdater 已是最新版本，无需升级。"
  # fi 
else
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "\033[1;36m MacUpdater 未安装，开始安装 ...\033[0m"
    echo -e "\033[1;36m-----------------------------------------------\033[0m" 
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "MacUpdater 未安装，开始安装 "                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "----------------------------------"                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    brew reinstall --cask --force macupdater 2>&1                                       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    if [ $? -eq 0 ]; then
        echo -e "MacUpdater 安装成功。"                                                 | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        echo -e ""                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    else
        echo -e "MacUpdater 安装失败。"                                                 | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        echo -e ""                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    fi
fi
    




# ----------------------------------
# 记录：开始时间
# ----------------------------------

# 等待3秒，开始执行
sleep 3  

# 记录当前时间戳（到$LOG_FILE）
echo -e "-------------------------------------------------"                             | tee -a "$LOG_FILE"  > /dev/null
echo -e "开始更新 APP: $(date)"                                                         | tee -a "$LOG_FILE"  > /dev/null

# 记录当前时间戳（到$$LOG_FULL_FILE），
echo -e  ""                                                                             | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
echo -e "\033[1;34m-----------------------------------------------\033[0m" 
echo -e "\033[1;34m 开始更新 APP: $(date)                         \033[0m"
echo -e "\033[1;34m-----------------------------------------------\033[0m" 
echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "开始更新 APP: $(date)"                                                         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e  ""                                                                             | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
echo -e  ""                                                                             | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"


# 此后，开始升级第三方APP！！！！！！此前都是在，检测环境 和更新 升级程序本身。



# -----------------------------------------------
# 在更新操作前：备份桌桌面布局（Launchpad）
# -----------------------------------------------

echo -e "\033[1;32m-----------------------------------------------\033[0m" 
echo -e "\033[1;32m 备份 桌面布局（Launchpad）                    \033[0m"
echo -e "\033[1;32m-----------------------------------------------\033[0m" 

echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "备份 桌面布局（Launchpad）"                                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null

# 备份 Launchpad 和 桌面布局
USER_NAME=$USER
BACKUP_PATH="$ICLOUD_PATH/BACKUP/$COMPUTER_NAME/$USER_NAME"
BACKUP_DATE=$(date +%Y-%m-%d)
PATH_DesktopLayout_BACKUP="$BACKUP_PATH/DesktopLayout/$BACKUP_DATE"
PATH_DesktopLayout_plist_SOURCE="$HOME/Library/Preferences"
USER_ID=$(basename "$(dirname "$TMPDIR")")
PARENT_DIR=$(find /System/Volumes/Data/private/var/folders/ -maxdepth 2 -type d -name "$USER_ID" 2>/dev/null)
PATH_DesktopLayout_db_SOURCE="$PARENT_DIR/0"

mkdir -p "$PATH_DesktopLayout_BACKUP"
cp -rf "$PATH_DesktopLayout_plist_SOURCE/com.apple.spaces.plist" "$PATH_DesktopLayout_BACKUP/"
cp -rf "$PATH_DesktopLayout_plist_SOURCE/com.apple.dock.plist" "$PATH_DesktopLayout_BACKUP/"
sudo cp -rf "$PATH_DesktopLayout_db_SOURCE/com.apple.dock.launchpad" "$PATH_DesktopLayout_BACKUP/"
cd "$PATH_DesktopLayout_BACKUP"
sudo chmod -R 755 "./com.apple.dock.launchpad"

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

printf  "\033[1;34m[Info]\033[0m "
printf  "[Info] "                                                                       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "桌面布局 备份路径：'$PATH_DesktopLayout_BACKUP'"                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

printf  "\033[1;34m[Info]\033[0m "
printf  "[Info] "                                                                       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "桌面布局 恢复路径: '$PATH_DesktopLayout_db_SOURCE'"                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

#printf  "\033[1;34m[Info]\033[0m "
#printf  "[Info] "                                                                       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
#printf  "桌面布局 备份文件: \n"                                                         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
#ls "$PATH_DesktopLayout_BACKUP"                                                         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

#echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
#echo -e "PARENT_DIR: $PARENT_DIR"                                                       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
#echo -e "USER_ID: $USER_ID"                                                             | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
#echo -e "TMPDIR: $TMPDIR"                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
echo -e "\033[1;32m[OK]   桌面布局 备份已完成 ✅ \033[0m"
echo -e "[OK]   桌面布局 备份已完成 ✅ "                                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 


# ----------------------------------
# 开始执行：HomeBrew
# ----------------------------------

export HOMEBREW_NO_INTERACTIVE=1


echo -e "\033[1;32m-----------------------------------------------\033[0m" 
echo -e "\033[1;32m 运行 HomeBrew ...                             \033[0m"
echo -e "\033[1;32m-----------------------------------------------\033[0m" 

echo -e "----------------------------------"                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "运行 HomeBrew"                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "----------------------------------"                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null

echo -e ""                                                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 

# 等待3秒，开始执行
sleep 3  


# 调用检查时间范围函数
check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"

# 第 1 步：获取所有需要更新的 公式 和 包名称
printf  "\033[1;34m[Scan]\033[0m "
printf  "[Scan] "                                                                     | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "扫描哪些软件需要更新 ... ( brew upgrade --debug --verbose --greedy )"        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
brew_outdated=$(brew outdated --greedy 2>&1                                           | tee -a /dev/tty "$LOG_FULL_LAST" "$LOG_FULL_FILE" | awk '{print $1}') 
brew_outdated_formulas=$(brew outdated --formula --greedy 2>&1                                                                    | awk '{print $1}')
brew_outdated_casks=$(brew outdated  --cask --greedy 2>&1                                                                         | awk '{print $1}')

# 将需要更新的包分别存储
packages_brew=($brew_outdated)
packages_brew_formulas=()
for pkg in ${brew_outdated_formulas}; do
    [[ -n "$pkg" ]] && packages_brew_formulas+=("$pkg")
done
packages_brew_casks=()
for pkg in ${brew_outdated_casks}; do
    [[ -n "$pkg" ]] && packages_brew_casks+=("$pkg")
done

echo -e ""                                                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

# 如果有需要更新的 Homebrew 软件包，则执行下载
if [ ${#packages_brew[@]} -ne 0 ]; then
  # 第 2 步：并行下载（提高下载速度）
  printf "\033[1;34m[Download]\033[0m "
  printf "[Download] "                                                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
  echo -e "开始下载：HomeBrew formula / cask（并行）..."                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
  
  # 筛选需要下载的 formula 软件包：如果缓存中已有完整的新版本则跳过
  packages_to_fetch_formulas=()
  for pkg in "${packages_brew_formulas[@]}"; do
      [[ -z "$pkg" ]] && continue  # 跳过空名称项（以防万一）
      cache_path=$(brew --cache --formula "$pkg")
      if [ -f "$cache_path" ]; then
          local_sha=$(shasum -a 256 "$cache_path" | awk '{print $1}')
          expected_sha=$(brew info --json=v2 "$pkg" | grep -o '"sha256":"[0-9a-f]\{64\}"' | head -n 1 | cut -d '"' -f 4)
          if [ -n "$expected_sha" ] && [ "$local_sha" = "$expected_sha" ]; then
              echo "🔰 [跳过] 已缓存 最新版本 [formula] ：$pkg "                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
              continue  # 略过重新下载
          fi
      fi
      packages_to_fetch_formulas+=("$pkg")
  done
  
  # 筛选需要下载的 cask 软件包：如果缓存中已有完整的新版本则跳过
  packages_to_fetch_casks=()
  for pkg in "${packages_brew_casks[@]}"; do
      [[ -z "$pkg" ]] && continue  # 跳过空名称项
      cache_path=$(brew --cache --cask "$pkg")
      if [ -f "$cache_path" ]; then
          local_sha=$(shasum -a 256 "$cache_path" | awk '{print $1}')
          expected_sha=$(brew info --cask --json=v2 "$pkg" 2>/dev/null | grep -o '"sha256":"[0-9a-f]\{64\}"' | head -n 1 | cut -d '"' -f 4)
          # 某些 cask 没有 SHA 信息（:latest 或 auto_updates），则不强制校验
          if [[ "$expected_sha" == "null" || -z "$expected_sha" ]]; then
              echo "🔰 [跳过] 已缓存 无校验版 [cask] ：$pkg "                           | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
              continue 
          fi 
          if [[ "$local_sha" == "$expected_sha" ]]; then 
              echo "🔰 [跳过] 已缓存 最新版本 [cask]  ：$pkg "                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
              continue
          fi
      fi
      packages_to_fetch_casks+=("$pkg")
  done
  
  # 并行下载需要更新的 formula 和 cask（使用 --retry 自动校验缓存有效性） 注意，与 下面的 parallel 方案 二选一。建议使用Parallel，因为速度更快。
  # printf '%s\n' "${packages_to_fetch_formulas[@]}" | xargs -n1 -P16 brew fetch --formula --retry         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
  # printf '%s\n' "${packages_to_fetch_casks[@]}"    | xargs -n1 -P8 brew fetch --cask --retry             | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

  # 确保 GNU Parallel 已安装（macOS 可通过 Homebrew 安装）
  if ! command -v parallel &>/dev/null; then
      brew install parallel   # 安装 GNU Parallel 并行执行工具 [oai_citation:3‡formulae.brew.sh](https://formulae.brew.sh/formula/parallel#:~:text=Install%20command%3A)
  fi
  
  # 并行下载 formula （最多16个并发），每个任务完成后输出状态 （使用 --retry 自动校验缓存有效性）
  if [ ${#packages_to_fetch_formulas[@]} -gt 0 ]; then
    parallel --will-cite --line-buffer --unsafe -j16 \
        "if brew fetch --formula --retry {} 2>&1 | tee -a '$LOG_FULL_LAST' '$LOG_FULL_FILE'; then echo -e '✅  下载成功 [formula] ：{} '| tee -a '$LOG_FULL_LAST' '$LOG_FULL_FILE' ; else echo -e '❌  下载失败 [formula] ：{} ' | tee -a '$LOG_FULL_LAST' '$LOG_FULL_FILE' ; fi" \
        ::: "${packages_to_fetch_formulas[@]}" &
  fi

  # 并行下载 cask    （最多16个并发），每个任务完成后输出状态 （使用 --retry 自动校验缓存有效性）
  if [ ${#packages_to_fetch_casks[@]} -gt 0 ]; then
    parallel --will-cite --line-buffer --unsafe -j16 \
        "if brew fetch --cask --retry {} 2>&1 | tee -a '$LOG_FULL_LAST' '$LOG_FULL_FILE'; then echo -e '✅  下载成功 [cask] ：{} ' | tee -a '$LOG_FULL_LAST' '$LOG_FULL_FILE' ; else echo -e '❌  下载失败 [cask] ：{} ' | tee -a '$LOG_FULL_LAST' '$LOG_FULL_FILE'; fi" \
        ::: "${packages_to_fetch_casks[@]}" &
  fi
  
  wait  # 等待所有并行任务完成
 #echo -e "✅ 所有下载任务 已完成/已退出"                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 

  # exit 0        # 用于调试 ！！

  # 第 3 步：串行安装（Homebrew formula）
  if [ ${#packages_brew_formulas[@]} -ne 0 ] ; then
      echo -e ""                                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
      printf "\033[1;34m[Install]\033[0m "
      printf "[Install] "                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
      echo -e "开始更新：HomeBrew formula（串行）..."                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

      # 循环逐个处理每个过期的 Homebrew formula
      for formula in "${packages_brew_formulas[@]}"; do
          # ---------- 尝试升级 ----------
          brew upgrade --force "$formula" 2>&1                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
          upgrade_exit=${PIPESTATUS[0]}        # 取 brew upgrade 的退出码
          final_exit=$upgrade_exit             # 先假定最终状态 = 升级状态

          # ---------- 若升级失败则尝试重装 ----------
          if [ $upgrade_exit -ne 0 ] ; then
              echo -e "upgrade 失败，尝试 reinstall：$formula ..."                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
              brew reinstall "$formula" 2>&1                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
              reinstall_exit=${PIPESTATUS[0]}  # 取 brew reinstall 的退出码
              final_exit=$reinstall_exit
          fi

          # ---------- 根据最终状态输出结果 ----------
          if [ $final_exit -eq 0 ] ; then
              echo -e "✅  更新成功 [formula] ：$formula"                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
              echo -e "--------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
          else  
              echo -e "❌  更新失败 [formula] ：$formula"                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
              echo -e "--------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
          fi
      done
  else
      echo -e ""                                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
      printf "\033[1;34m[Install]\033[0m "
      printf "[Install] "                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
      echo -e "无需更新：HomeBrew formula ..."                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
      echo -e ""                                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
  fi

  # 第 4 步：串行安装（Homebrew cask）
  if [ ${#packages_brew_casks[@]} -ne 0 ] ; then
    printf  "\033[1;34m[Install]\033[0m "
    printf  "[Install] "                                                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    echo -e "开始更新：HomeBrew cask（串行 ）..."                                       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    # 逐个安装 每个待更新的 cask app
    for cask in $brew_outdated_casks; do
        # 利用 brew info 提取 Cask 安装的 .app 应用包名称
        app_line=$(brew info --cask "$cask" | grep -m1 '\.app (App)')
        # 上述命令从 brew info 输出中找出包含“.app (App)”的行，并去掉后面的标记，取得应用程序包名
        app_name=$(echo "$app_line" | sed -e 's/\.app (App)//' -e 's/^[[:space:]]*//')
        # **初始化 was_running 标志**
        was_running=false
        # 确认提取到的应用名不为空
        if [[ -n "$app_name" ]]; then
            # 如果该应用正在运行，先尝试退出
            if pgrep -ix "$app_name" > /dev/null; then
                echo -e "检测到 $app_name 正在运行，尝试退出应用..."                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
               # 组合命令，用 () 分组，再把 stderr 合并到 stdout 后送给 tee 
                ( osascript -e "tell application \"$app_name\" to quit" || killall "$app_name" ) 2>&1         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
                sleep 5  # 等待数秒让应用完全退出   
                was_running=true    
            fi  
        else    
            echo "⚠️ 警告：无法从 brew info 提取 $cask 的应用名称，无法自动关闭应用，将直接升级。"              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        fi  

        # 升级 cask 应用    
        brew upgrade --cask --greedy "$cask" 2>&1                                       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        upgrade_exit=${PIPESTATUS[0]}           # 获取 brew upgrade 的退出码    
        final_exit=$upgrade_exit               # 先假定最终状态为 upgrade 的状态    

        if [ $upgrade_exit -ne 0 ]; then    
            echo -e "⚠️ upgrade 升级失败，$cask，尝试使用 reinstall 重新安装..."        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
            brew reinstall --cask --force "$cask" 2>&1                                  | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
            reinstall_exit=${PIPESTATUS[0]}    # 获取 brew reinstall 的退出码   
            #  -------- 以下代码 未验证  如遇问题请关闭 -------- #
            if [ $reinstall_exit -ne 0 ]; then
                # 若重装失败且检测到应用仍在运行，强制关闭后再重试一次
                if pgrep -ix "$app_name" > /dev/null; then
                    echo -e "⚠️ 检测到 $app_name 仍在运行，强制关闭后再次尝试安装..."   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
                    pid=$(pgrep -f "$app_name")
                    if [ -n "$pid" ]; then
                        kill -9 "$pid"
                    fi
                    brew reinstall --cask --force "$cask" 2>&1                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
                    reinstall_exit=${PIPESTATUS[0]}
                fi
            fi
            #  -------- 以上代码 未验证  如遇问题请关闭 -------- #
            final_exit=$reinstall_exit       # 将最终状态更新为 reinstall 的状态  
        fi  

        # 如果之前关闭了应用，更新完成后重新打开 
        if [[ "$was_running" = true && -n "$app_name" ]]; then  
            echo "重新启动此前关闭的应用：$app_name ..."                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
            open -a "$app_name" 2>&1                                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        fi

        # 根据最终状态输出结果（成功或失败），然后继续处理下一个 cask
        if [ $final_exit -eq 0 ]; then
            echo "✅  更新成功 [cask] : $cask."                                         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        else    
            echo "❌  更新失败 [cask] : $cask."                                         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
        fi
        echo -e "--------------------"                                                  | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    done
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
  else  
    printf  "\033[1;34m[Install]\033[0m "   
    printf  "[Install] "                                                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"  > /dev/null
    echo -e "无需更新：HomeBrew cask ..."                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
    echo -e ""                                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
  fi    

 #brew upgrade --greedy --debug --force                                                 | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE""  ###### 仅作为Debug使用！！！

else    
  printf  "\033[1;34m[Download & Install]\033[0m "    
  printf  "[Download & Install] "                                                       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
  echo -e "当前没有需要更新的 Homebrew 包 !!! "                                         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
  echo -e ""                                                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
fi


# 第 5 步： 清洁
printf  "\033[1;34m[Clean]\033[0m "
printf  "[Clean] "                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "清理 Homebrew 残留 ..."                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
brew cleanup --prune=all 2>&1                                                           | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
brew autoremove 2>&1                                                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

echo -e "\033[1;32m[OK] Homebrew 更新已完成  ✅\033[0m"
echo -e "[OK] Homebrew 更新已完成"                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 

# ----------------------------------
# 开始执行：Mas
# ----------------------------------

export Mas_NO_INTERACTIVE=1

echo -e ""                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

echo -e "\033[1;32m-----------------------------------------------\033[0m" 
echo -e "\033[1;32m 运行 Mas ...                                  \033[0m"
echo -e "\033[1;32m-----------------------------------------------\033[0m" 

echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "运行 Mas"                                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
  
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

# 等待3秒，开始执行
sleep 3  

# 调用检查时间范围函数（假设此函数已定义）
check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"

# 显示未更新APP列表：Mas （并捕获输出）
printf  "\033[1;34m[Scan] \033[0m"
printf  "[Scan] "                                                                       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "扫描更新 ... "                                                                 | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
outdated_mas_apps=$( mas outdated ) 
echo "$outdated_mas_apps"                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 


# 开始执行：Mas 更新（并捕获输出）
printf  "\033[1;34m[Download & Install]\033[0m "
printf  "[Download & Install] "                                                         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e " 下载 & 安装 ..."                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

# 获取过时应用程序的ID
app_ids=$(echo -e "$outdated_mas_apps" | awk '{print $1}'  | grep -E '^[0-9]+$')
# 获取已安装应用程序的列表
installed_apps=$( mas list )
# 存储需要关闭和重启的应用程序
apps_to_restart=()

# 检查并关闭正在运行的应用程序
for id in $app_ids; do
  # 从已安装应用列表中提取应用名称，去掉ID和可能的版本号
  app_name=$(echo -e "$installed_apps" | grep "^$id" | awk '{$1=""; print substr($0,2)}' | sed 's/ ([0-9].*)$//')
  if [ -n "$app_name" ]; then
    # 使用 osascript 检查应用是否正在运行
    if osascript -e "tell application \"System Events\" to (name of processes) contains \"$app_name\"" | grep -q "true"; then
      echo -e "检测到 $app_name 正在运行，正在尝试关闭..."                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
      # 安全关闭应用程序
      osascript -e "tell application \"$app_name\" to quit"
      # 等待应用完全关闭（最多10秒）
      for i in {1..10}; do
        if ! osascript -e "tell application \"System Events\" to (name of processes) contains \"$app_name\"" | grep -q "true"; then
          break
        fi
        sleep 1
      done
      # 如果应用仍未关闭，尝试强制关闭
      if osascript -e "tell application \"System Events\" to (name of processes) contains \"$app_name\"" | grep -q "true"; then
        echo -e "无法正常关闭 $app_name，正在尝试强制关闭..."                         | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        # 获取应用程序的PID
        pid=$(pgrep -f "$app_name")
        if [ -n "$pid" ]; then
          kill -9 $pid
          echo -e "已强制关闭 $app_name (PID: $pid)"                                  | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        else
          echo -e "无法获取 $app_name 的PID，跳过强制关闭"                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
        fi
      fi
      # 再次检查应用是否已关闭成功
      if osascript -e "tell application \"System Events\" to (name of processes) contains \"$app_name\"" | grep -q "true"; then
        echo -e "✘  $app_name 无法关闭，跳过重启该应用。"                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
      else
        # 已成功关闭的应用加入重启列表
        apps_to_restart+=("$app_name")
        echo -e "✓  $app_name 已关闭，稍后将重新启动。"                                | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
      fi
    fi
  fi
done

# 开始更新 MAS（Mac App Store APP）
mas upgrade 2>&1                                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

# 重新启动之前关闭的应用程序
for app in "${apps_to_restart[@]}"; do
  echo -e "✓ 正在重新启动 $app..."                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
  open -a "$app"                                                                        | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
  sleep 1  # 短暂延迟以确保应用启动
done
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 

echo -e "\033[1;32m[OK] Mas 更新已完成，APP 已重启  ✅\033[0m"
echo -e "[OK] Mas 更新已完成，APP 已重启"                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 






# ----------------------------------
# 开始执行：MacPorts
# ----------------------------------

export MacPorts_NO_INTERACTIVE=1

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 

echo -e "\033[1;32m-----------------------------------------------\033[0m"  
echo -e "\033[1;32m 运行 MacPorts ...                             \033[0m"  
echo -e "\033[1;32m-----------------------------------------------\033[0m"  

echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "运行 MacPorts"                                                                 | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 

# 等待3秒，开始执行
sleep 3  

# 调用检查时间范围函数
check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"

# 执行：MacPorts （并捕获输出）
sudo port upgrade outdated -N 2>&1                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 





# ----------------------------------
# MacOS System Update
# ----------------------------------

export SoftwareUpdate_NO_INTERACTIVE=1

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

echo -e "\033[1;32m-----------------------------------------------\033[0m"  
echo -e "\033[1;32m 运行 MacOS System Update ...                  \033[0m"  
echo -e "\033[1;32m-----------------------------------------------\033[0m"  

echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "运行 MacOS System Update"                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

# 等待3秒，开始执行 
sleep 3     

# 调用检查时间范围函数  
check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE" 

# 自动执行：SoftwareUpdate （并捕获输出）   
softwareupdate --list --force 2>&1                                                      | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
softwareupdate --download --force 2>&1                                                  | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
# softwareupdate --install --all --force --verbose   
# 注意：安装更新会强制要求输入密码，无法免密，所以，建议只下载，再通过系统的自动更细功能进行更新

#echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"





# ----------------------------------
# 开始执行：TopGrade
# ----------------------------------

export TopGrade_NO_INTERACTIVE=1

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

echo -e "\033[1;32m-----------------------------------------------\033[0m"  
echo -e "\033[1;32m 运行 TopGrade ...                             \033[0m"  
echo -e "\033[1;32m-----------------------------------------------\033[0m"  

echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "运行 TopGrade"                                                                 | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

# 等待3秒，开始执行
sleep 3  

# 调用检查时间范围函数
check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"

# 执行 TopGrade （并捕获输出）
topgrade --disable brew_formula --disable brew_cask --disable mas --disable system --disable macports --yes --cleanup 2>&1  | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"   # 不执行 Homebrew更新 +  不执行 Mas更新 （前面已更新过，且tograde的homebrew更新不会调用--greedy参数对通过homebrew安装的APP进行足量更新）
brew cleanup --prune=all 2>&1                                                           | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
brew autoremove 2>&1                                                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"

echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 





# ----------------------------------
# 开始执行： MacUpdater
# ----------------------------------

#export MacUpdater_NO_INTERACTIVE=1
#
#echo -e "\033[1;32m-----------------------------------------------\033[0m" 
#echo -e "\033[1;32m 运行 MacUpdater ...                           \033[0m"
#echo -e "\033[1;32m-----------------------------------------------\033[0m" 
#
#echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
#echo -e "运行 MacUpdater"                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
#echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
#
#echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
#
## 等待3秒，开始执行
#sleep 3  
#
## 调用检查时间范围函数
#check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"
#
## 执行MacUpdater扫描 （已安装的APP）
## "/Applications/MacUpdater.app/Contents/Resources/macupdater_client" scan --quiet 2>&1 | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
#
## 获取已安装应用的总数
#echo -e "获取已安装的应用列表..."                                                       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
## TOTAL_APPS=$("$MACUPDATER_CLIENT" list | wc -l)
#TOTAL_APPS=$("/Applications/MacUpdater.app/Contents/Resources/macupdater_client" list | wc -l)
#echo -e "APP 数量（全部总计）: $TOTAL_APPS"                                             | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
## TOTAL_APPS=$("/Applications/MacUpdater.app/Contents/Resources/macupdater_client" list --hide-mas-apps --hide-unsupported-apps | wc -l)
## echo -e "APP 数量（支持更新）: $TOTAL_APPS"                                           | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
#
## 执行扫描命令（并显示进度条）
#run_command_with_show_progress "\"$MACUPDATER_CLIENT\" scan" "SCAN"  "$LOG_MACUPDATER_FILE"
#
## 执行更新命令
#"/Applications/MacUpdater.app/Contents/Resources/macupdater_client" update --force-quit-running-apps --force-major-version-update 2>&1                  | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
##"/Applications/MacUpdater.app/Contents/Resources/macupdater_client" update --force-quit-running-apps 2>&1                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
#
#echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
#echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 




# ----------------------------------
# 恢复 桌面布局（Launchpad）
# ----------------------------------
# 在所有更新操作完成后，调用桌面布局（Launchpad）恢复脚本，恢复之前保存的布局
#trap - EXIT  # 取消先前设置的 trap，避免重复恢复
echo -e "\033[1;32m-----------------------------------------------\033[0m" 
echo -e "\033[1;32m 恢复 桌面布局（Launchpad）                    \033[0m"
echo -e "\033[1;32m-----------------------------------------------\033[0m" 

echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "恢复 桌面布局（Launchpad）"                                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    
output=$(restore_desktop_layout 2>&1)   
status=$?   
echo "$output"                                  
    
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    
if [ $status -ne 0 ]; then  
  printf  "\033[1;34m[Info]\033[0m "
  printf  "[Info] "                                                                     | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
  echo -e "桌面布局 恢复路径: '$PATH_DesktopLayout_db_SOURCE'"                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
  printf  "\033[1;34m[Info]\033[0m "
  printf  "[Info] "                                                                     | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
  echo -e "桌面布局 备份路径：'$PATH_DesktopLayout_BACKUP'"                             | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
  printf  "\033[1;34m[ERROR]\033[0m "   
  printf  "[ERROR] "                                                                    | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
  echo -e "桌面布局 恢复失败，请手动恢复 ❌"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" "$LOG_ERROR_FILE"
else    
  echo -e "\033[1;32m[OK] 桌面布局 恢复已完成 \033[1;32m✅"   
  echo -e "[OK]   桌面布局 恢复已完成 ✅ "                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
fi  
    
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE"





# ----------------------------------
# 记录：完成时间 
# ----------------------------------

# 最后打印执行完成的时间

echo -e "\033[1;32m-----------------------------------------------\033[0m" 
echo -e "\033[1;32m 已完成 所有更新  ...                          \033[0m"
echo -e "\033[1;32m-----------------------------------------------\033[0m" 

echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "已完成 所有更新"                                                               | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
echo -e "----------------------------------"                                            | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
    
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    
echo -e "日志路径： '$LOG_PATH' "                                                       | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
    
echo -e "\033[1;32mFinished at: $(date) \033[0m"    
echo -e "Finished at: $(date)"                                                          | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" "$LOG_FILE" > /dev/null
    
# 打开Log日志文件夹 
open "$LOG_PATH"    
    
    
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
echo -e ""                                                                              | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 




